import SdkNavbar from "@/components/navbar";
import type { Metadata } from "next";


export const metadata: Metadata = {
  title: "Landing Page",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={``}>
        <SdkNavbar/>
        <section className="hero_section">
          {children}
        </section>
      </body>
    </html>
  );
}